import React, { useState, useEffect } from 'react';
import { Container, Typography, Box, Link, Paper, CircularProgress, Alert } from '@mui/material';
import { Link as RouterLink } from 'react-router-dom';
import ResumeData from './resume.json';

// Try to import the notebooks manifest (generated by script)
let notebooksManifest = null;
try {
  // eslint-disable-next-line import/no-unresolved
  notebooksManifest = require('./notebooks-manifest.json');
} catch (error) {
  console.warn('Notebooks manifest not found. Run "npm run generate-notebooks-manifest" to generate it.');
}

function Blog() {
  const [notebooks, setNotebooks] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (notebooksManifest && notebooksManifest.notebooks) {
      setNotebooks(notebooksManifest.notebooks);
      setLoading(false);
    } else {
      setLoading(false);
    }
  }, []);

  return (
    <Container maxWidth="md" sx={{ py: 4, position: 'relative' }}>
      <Link
        component={RouterLink}
        to="/"
        sx={{
          position: 'absolute',
          top: 16,
          left: 16,
          color: '#1e40af',
          textDecoration: 'none',
          fontFamily: "'Source Serif 4', serif",
          fontSize: '1rem',
          '&:hover': {
            textDecoration: 'underline',
          },
        }}
      >
        ← Home
      </Link>
      <Box>
        <Typography 
          variant="h3" 
          component="h1" 
          gutterBottom
          sx={{ fontFamily: "'Source Serif 4', serif" }}
        >
          Blog
        </Typography>
        <Typography 
          variant="body1" 
          color="text.secondary" 
          sx={{ mb: 2, fontFamily: "'Source Serif 4', serif" }}
        >
          They say the best way to learn about something is to build it yourself. This blog captures my attempts to learn, well, just about anything. Hope you enjoy!
        </Typography>
        <Typography 
          variant="body1" 
          color="text.secondary" 
          sx={{ mb: 4, fontFamily: "'Source Serif 4', serif", fontStyle: 'italic' }}
        >
          Runnable code for all these blogs is available on my{' '}
          <Link
            href={ResumeData.info.profile}
            target="_blank"
            rel="noreferrer"
            sx={{
              color: '#1e40af',
              textDecoration: 'none',
              fontFamily: "'Source Serif 4', serif",
              '&:hover': {
                textDecoration: 'underline',
              },
            }}
          >
            GitHub
          </Link>
          .
        </Typography>

        {loading ? (
          <Box sx={{ display: 'flex', justifyContent: 'center', py: 4 }}>
            <CircularProgress />
          </Box>
        ) : notebooks.length === 0 ? (
          <Alert severity="info" sx={{ mb: 3 }}>
            <Typography variant="body2" sx={{ fontFamily: "'Source Serif 4', serif" }}>
              No notebooks found. Place your <code>.ipynb</code> files in the <code>public/notebooks/</code> directory 
              and run <code>npm run generate-notebooks-manifest</code> to update the list.
            </Typography>
          </Alert>
        ) : (
          <Box sx={{ mb: 4 }}>
            {notebooks.map((notebook, index) => (
              <Paper
                key={index}
                component={RouterLink}
                to={`/notebook/${encodeURIComponent(notebook.filename)}`}
                elevation={1}
                sx={{
                  p: 3,
                  mb: 3,
                  display: 'block',
                  textDecoration: 'none',
                  color: 'inherit',
                  cursor: 'pointer',
                  transition: 'box-shadow 0.2s ease, background-color 0.2s ease',
                  '&:hover': {
                    boxShadow: 3,
                    backgroundColor: 'action.hover',
                  },
                }}
              >
                <Typography 
                  variant="h5" 
                  gutterBottom
                  sx={{ fontFamily: "'Source Serif 4', serif" }}
                >
                  {notebook.title}
                </Typography>
                {notebook.lastModified && (
                  <Typography 
                    variant="caption" 
                    color="text.secondary"
                    sx={{ display: 'block', mb: 1.5, fontFamily: "'Source Serif 4', serif" }}
                  >
                    {new Date(notebook.lastModified).toLocaleDateString('en-US', {
                      year: 'numeric',
                      month: 'long',
                      day: 'numeric',
                    })}
                  </Typography>
                )}
                {notebook.description && (
                  <Typography 
                    variant="body2" 
                    color="text.secondary" 
                    sx={{ fontFamily: "'Source Serif 4', serif" }}
                  >
                    {notebook.description}
                  </Typography>
                )}
              </Paper>
            ))}
          </Box>
        )}
      </Box>
    </Container>
  );
}

export default Blog;

